name: city_picker_example
description: Demo for how to use the city_pickers plugin.

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  flutter_city_picker:
    path: ../
  provider: ^6.1.5+1
  dio: ^5.9.0
  flutter_colorpicker: ^1.1.0
  lpinyin: ^2.0.3

flutter:

  uses-material-design: true

  assets:
    - assets/data.json
